@startuml
'https://plantuml.com/class-diagram

class RecyclerView.ViewHolder

class BookViewHolder {
    bookView: CardView
    bookPreviewView: ImageView
    bookTitleView: TextView
    bookAuthorView: TextView
    bookExtensionView: TextView
    bookSizeView: TextView
}

RecyclerView.ViewHolder <|-- BookViewHolder


@enduml